#========================================
#    sl.c: SL version 5.02
#        Copyright 1993,1998,2014
#                  Toyoda Masashi
#                  (mtoyoda@acm.org)
#        Last Modified: 2014/06/03
#========================================

CC=gcc
CFLAGS=-O

sl: sl.c sl.h
	$(CC) $(CFLAGS) -o sl sl.c -lncurses
